name: Node.js CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Choose global or local node modules caching
      # https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

      # - name: Use dependencies cache
      #   id: cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ./node_modules
      #     key: modules-${{ hashFiles('package-lock.json') }}

      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: npm ci --ignore-scripts

      - name: Use dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts
